apiVersion: v1
kind: Service
metadata:
  name: {{ include "tf-serving-chart.fullname" . }}
  labels:
    {{- include "tf-serving-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc-port # Maps to containerPort 8500
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.restPort }}
      targetPort: rest-port # Maps to containerPort 8501
      protocol: TCP
      name: http
  selector:
    {{- include "tf-serving-chart.selectorLabels" . | nindent 4 }}
